trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: test
    displayName: Deploy to Test
    jobs:
      - job: Test
        displayName: Test
        steps:
          - checkout: self
            fetchDepth: 1

          - template: installDependencies.yaml

          - task: AzureCLI@2
            displayName: Run build.sh test ---no-input
            inputs:
              azureSubscription: AlvNo-Dev
              addSpnToEnvironment: true
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Authenticate Acure container registry
                docker login acralvtime.azurecr.io \
                  --username $servicePrincipalId \
                  --password $servicePrincipalKey

                # Run scripts to build for test environment
                ./run deploy test website $BUILD_BUILDID
