trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  subscriptionId: '32547ca3-abba-45c8-b76e-46a590958b5e'
  serviceName: alvnodev
  serviceConnection: AlvNo-Dev
  envFileName: '.env.development'

stages:
  - stage: build
    displayName: Build and test
    jobs:
      - job: githash
        displayName: Build
        steps:
          - task: Bash@3
            name: createHash
            displayName: Create hash
            inputs:
              targetType: inline
              script: |
                ## At least 7 digits, more if needed for uniqueness
                SHORT_HASH=`git rev-parse --short=7 HEAD`
                echo "Short hash set to $SHORT_HASH"
                echo "##vso[task.setvariable variable=git-short-hash;isOutput=true]$SHORT_HASH"

          - template: ../../packages/infrastructure/build-steps.yaml

  - stage: test
    displayName: Deploy to Test
    jobs:
      - deployment: Test
        variables:
          subscriptionId: '32547ca3-abba-45c8-b76e-46a590958b5e'
          serviceName: alvnodev
          serviceConnection: AlvNo-Dev
          envFileName: '.env.development'
          git-short-hash: $[ stageDependencies.build.githash.outputs['createHash.git-short-hash'] ]
        displayName: Test
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../../packages/infrastructure/deploy-steps.yaml

  - stage: prod
    displayName: Deploy to Production
    jobs:
      - deployment: Prod
        variables:
          subscriptionId: '98aa1177-a37b-4349-a01f-8f1d325064c3'
          serviceName: alvno
          serviceConnection: AlvNo-Prod(98aa1177-a37b-4349-a01f-8f1d325064c3)
          envFileName: '.env.production'
          git-short-hash: $[ stageDependencies.build.githash.outputs['createHash.git-short-hash'] ]
        displayName: Prod
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../../packages/infrastructure/deploy-steps.yaml
