trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  subscriptionId: '32547ca3-abba-45c8-b76e-46a590958b5e'
  serviceName: alvnodev
  serviceConnection: AlvNo-Dev
  envFileName: '.env.production'

stages:
  - stage: test
    displayName: Deploy to Test
    jobs:
      - job: Test
        displayName: Test
        variables:
          subscriptionId: '32547ca3-abba-45c8-b76e-46a590958b5e'
          serviceName: alvnodev
          serviceConnection: AlvNo-Dev
          hostname: "dev.alv.no"
          envFileName: '.env.production'
        steps:
          - template: ../../packages/infrastructure/deploy-steps.yaml
