trigger:
  - prod

pr: none

# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#cron-syntax
schedules:
- cron: "30 10 * * 2"
  displayName: Thusdays at 1030
  branches:
    include:
    - prod
  always: true
- cron: "0 16 * * 4"
  displayName: Thursday at 1600
  branches:
    include:
    - prod
  always: true

pool:
  vmImage: ubuntu-latest

variables:
  subscriptionId: '32547ca3-abba-45c8-b76e-46a590958b5e'
  serviceName: alvnodev
  serviceConnection: AlvNo-Dev
  envFileName: '.env.production'

stages:
  - stage: prod
    displayName: Deploy to Production
    jobs:
      - job: Prod
        displayName: Prod
        variables:
          subscriptionId: '98aa1177-a37b-4349-a01f-8f1d325064c3'
          serviceName: alvno
          serviceConnection: AlvNo-Prod(98aa1177-a37b-4349-a01f-8f1d325064c3)
          hostname: "alv.no"
          envFileName: '.env.production'
        steps:
          - template: ../../packages/infrastructure/deploy-steps.yaml
