trigger:
  branches:
    include:
      - master

  paths:
    include:
      - packages/video-party
pr: none

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: prod
    displayName: Deploy to Production
    variables:
      - group: azure-credentials-prod
    jobs:
      - deployment: Prod
        displayName: Prod
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1

                - template: installDependencies.yaml

                - task: Bash@3
                  displayName: ./run deploy prod video-party $BUILD_BUILDID
                  env:
                    AZURE_SERVICE_PRINCIPAL_USERNAME: $(azure-service-principal-username)
                    AZURE_SERVICE_PRINCIPAL_PASSWORD: $(azure-service-principal-password)
                    AZURE_TENANT_ID: $(azure-tenant-id)
                    AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
                  inputs:
                    targetType: "inline"
                    script: |
                      az login --service-principal \
                        --username "$AZURE_SERVICE_PRINCIPAL_USERNAME" \
                        --password "$AZURE_SERVICE_PRINCIPAL_PASSWORD" \
                        --tenant "$AZURE_TENANT_ID"

                      az account set --subscription $AZURE_SUBSCRIPTION_ID

                      # Authenticate Acure container registry
                      docker login alvkubernetesclustertestacr.azurecr.io \
                        --username $AZURE_SERVICE_PRINCIPAL_USERNAME \
                        --password $AZURE_SERVICE_PRINCIPAL_PASSWORD

                      # Run scripts to build for prod environment
                      ./run deploy prod video-party $BUILD_BUILDID
