trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: packageDiractory
    value: '$(System.DefaultWorkingDirectory)/packages/infrastructure/stage-1'

  - name: subscriptionIdDev
    value: '32547ca3-abba-45c8-b76e-46a590958b5e'

  - name: serviceName
    value: 'alvnodev'

jobs:
  - job: Deploy
    steps:
      - task: Bash@3
        name: createHash
        displayName: Create hash
        inputs:
          targetType: inline
          script: |
            ## At least 7 digits, more if needed for uniqueness
            SHORT_HASH=`git rev-parse --short=7 HEAD`
            echo "Short hash set to $SHORT_HASH"
            echo "##vso[task.setvariable variable=git-short-hash;isOutput=true]$SHORT_HASH"

      - task: TerraformInstaller@0
        displayName: Install Terraform v0.14.7
        inputs:
          terraformVersion: '0.14.7'

      - task: TerraformTaskV1@0
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'AlvNo-Dev'
          backendAzureRmResourceGroupName: 'Common'
          backendAzureRmStorageAccountName: '$(serviceName)'
          backendAzureRmContainerName: 'terraformstatus'
          backendAzureRmKey: 'terraform.tfstate'
          workingDirectory: '$(packageDiractory)'

      - task: TerraformTaskV1@0
        displayName: Terraform validate
        inputs:
          provider: azurerm
          command: validate
          workingDirectory: '$(packageDiractory)'

      - task: TerraformTaskV1@0
        displayName: Terraform plan -out=tfplan
        inputs:
          provider: azurerm
          command: plan
          commandOptions: '-var "docker_tag=$(git-short-hash)" -var "subscription_id=$(subscriptionIdDev)" -var "service_name=$(serviceName)" -out=tfplan'
          environmentServiceNameAzureRM: 'AlvNo-Dev'
          workingDirectory: $(packageDiractory)

      - task: TerraformTaskV1@0
        displayName: Terraform apply tfplan
        inputs:
          provider: azurerm
          command: apply
          commandOptions: tfplan
          environmentServiceNameAzureRM: 'AlvNo-Dev'
          workingDirectory: '$(packageDiractory)'
