trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: test
    displayName: Deploy to Test
    variables:
      - group: azure-credentials-test
    jobs:
      - job: Test
        displayName: Test
        steps:
          - checkout: self
            fetchDepth: 1

          - template: installDependencies.yaml

          - task: Bash@3
            displayName: ./run deploy test website $BUILD_BUILDID
            env:
              AZURE_SERVICE_PRINCIPAL_USERNAME: $(azure-service-principal-username)
              AZURE_SERVICE_PRINCIPAL_PASSWORD: $(azure-service-principal-password)
              AZURE_TENANT_ID: $(azure-tenant-id)
              AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
            inputs:
              targetType: "inline"
              script: |
                az login --service-principal \
                  --username "$AZURE_SERVICE_PRINCIPAL_USERNAME" \
                  --password "$AZURE_SERVICE_PRINCIPAL_PASSWORD" \
                  --tenant "$AZURE_TENANT_ID"

                az account set --subscription $AZURE_SUBSCRIPTION_ID

                # Authenticate Acure container registry
                docker login alvkubernetesclustertestacr.azurecr.io \
                  --username $AZURE_SERVICE_PRINCIPAL_USERNAME \
                  --password $AZURE_SERVICE_PRINCIPAL_PASSWORD

                # Run scripts to build for test environment
                ./run deploy test website $BUILD_BUILDID
