# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: review
    displayName: Deploy to review
    variables:
      - group: azure-credentials-test
    jobs:
      - job: Review
        displayName: Review
        steps:
          - checkout: self
            fetchDepth: 1

          - template: installDependencies.yaml

          - task: Bash@3
            displayName: ./run deploy review website $BUILD_BUILDID $CI_ENVIRONMENT_SLUG
            env:
              AZURE_SERVICE_PRINCIPAL_USERNAME: $(azure-service-principal-username)
              AZURE_SERVICE_PRINCIPAL_PASSWORD: $(azure-service-principal-password)
              AZURE_TENANT_ID: $(azure-tenant-id)
              AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
              SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $(prnumber)
              SYSTEM_PULLREQUEST_SOURCEBRANCH: $(sourcebranch)
            inputs:
              targetType: 'inline'
              script: |
                echo $(prnumber)
                echo $(sourcebranch)
                az login --service-principal \
                  --username "$AZURE_SERVICE_PRINCIPAL_USERNAME" \
                  --password "$AZURE_SERVICE_PRINCIPAL_PASSWORD" \
                  --tenant "$AZURE_TENANT_ID"

                az account set --subscription $AZURE_SUBSCRIPTION_ID

                TRUNCATED_BUILD_SOURCEBRANCH=$(echo "${SYSTEM_PULLREQUEST_SOURCEBRANCH##*/}" | cut -c -10)
                TRUNCATED_SYSTEM_PULLREQUEST_PULLREQUESTNUMBER=$(echo "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" | cut -c -6)
                CI_ENVIRONMENT_SLUG="$TRUNCATED_BUILD_SOURCEBRANCH-$TRUNCATED_SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"

                # Run scripts to deploy review environment
                ./run undeploy review _ _ $CI_ENVIRONMENT_SLUG

                echo "Killed https://$CI_ENVIRONMENT_SLUG.review.test-alv.no"
                
