#!/usr/bin/env bash

# set -e;

# AZURE_SERVICE_PRINCIPAL_USERNAME: "f6d65e85-ba21-4f51-b4ba-ea93b5e04856"
# AZURE_SERVICE_PRINCIPAL_PASSWORD: ""
AZURE_TENANT_ID="76749190-4427-4b08-a3e4-161767dd1b73"
AZURE_SUBSCRIPTION_ID="18d83c2a-79e0-48b2-a49a-0244de28de8c"
SYSTEM_PULLREQUEST_PULLREQUESTNUMBER="123"
SYSTEM_PULLREQUEST_SOURCEBRANCH="some-branch"

script: |
  az login
  # az login --service-principal \
  #   --username "$AZURE_SERVICE_PRINCIPAL_USERNAME" \
  #   --password "$AZURE_SERVICE_PRINCIPAL_PASSWORD" \
  #   --tenant "$AZURE_TENANT_ID"

  az account set --subscription $AZURE_SUBSCRIPTION_ID

  # Authenticate Azure container registry
  docker login alvkubernetesclustertestacr.azurecr.io \
    --username $AZURE_SERVICE_PRINCIPAL_USERNAME \
    --password $AZURE_SERVICE_PRINCIPAL_PASSWORD

  TRUNCATED_BUILD_SOURCEBRANCH=$(echo "${SYSTEM_PULLREQUEST_SOURCEBRANCH##*/}" | cut -c -10)
  TRUNCATED_SYSTEM_PULLREQUEST_PULLREQUESTNUMBER=$(echo "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" | cut -c -6)
  CI_ENVIRONMENT_SLUG=$(echo "$TRUNCATED_BUILD_SOURCEBRANCH-$TRUNCATED_SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" | tr "/" "-" | tr "_" "-")

  # Run scripts to deploy review environment
  ./run deploy review website $BUILD_BUILDID $CI_ENVIRONMENT_SLUG $TRUNCATED_SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
  echo "Review environment deployed to https://$CI_ENVIRONMENT_SLUG.review.test-alv.no"
