version: "3.8"
services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      # Enables the Web UI
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
    ports:
      # Http
      - 80:80
      # Web UI
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  website:
    container_name: website
    build:
      context: ./
      dockerfile: website.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`website.localhost`)"
      - "traefik.dashboard.port=80"
    restart: unless-stopped

  cms:
    container_name: cms
    build:
      context: ./
      dockerfile: cms.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms.rule=Host(`cms.localhost`)"
      - "traefik.dashboard.port=80"
    restart: unless-stopped
