version: "3.8"
services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      # Enables the Web UI
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
    ports:
      # Http
      - 80:80
      # Web UI
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  dave:
    image: theknarf/dave
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dave.rule=Host(`localhost`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
  website:
    image: website
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`website.localhost`)"
      - "traefik.website.port=80"
      - "dave.relativeSubdomain=website"
    restart: unless-stopped

  cms:
    image: cms
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms.rule=Host(`cms.localhost`)"
      - "traefik.cms.port=80"
      - "dave.relativeSubdomain=cms"
    restart: unless-stopped

  mail-api:
    image: mail-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail-api.rule=Host(`mail-api.localhost`)"
      - "traefik.mail-api.port=80"
      - "dave.relativeSubdomain=mail-api"
    restart: unless-stopped
