name: Deploy test website

on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  ENV: test
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  KEY_VAULT: ${{ vars.KEY_VAULT_TEST }}
  TAG: some-random-hash-thingy-12345

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: "{ \"clientId\": ${{ secrets.AZURE_CLIENT_ID }}, \"clientSecret\": ${{ secrets.AZURE_CLIENT_SECRET }}, \"subscriptionId\": ${{ secrets.AZURE_SUBSCRIPTION_ID }}, \"tenantId\": ${{ secrets.AZURE_TENANT_ID }} }"
        id: azure_login

      - name: Get Secret from Azure Key Vault
        id: get_secrets
        run: |
          ALV_HOSTNAME=$(az keyvault secret show --vault-name $KEY_VAULT_TEST --name alv-hostname --query "value" -o tsv)
          SANITY_TOKEN=$(az keyvault secret show --vault-name $KEY_VAULT_TEST --name sanity-token --query "value" -o tsv)
          YT_API=$(az keyvault secret show --vault-name $KEY_VAULT_TEST --name youtube-api-token --query "value" -o tsv)

          echo "Secrets: $ALV_HOSTNAME, $SANITY_TOKEN, $YT_API"
        env:
          AZURE_CORE_OUTPUT: json

  # deploy-website:
  #   needs: get-secrets
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build, push and deploy
  #       shell: bash
  #       run: |
  #         source ./packages/website/website-service.sh
  #         buildWebsite \
  #           $ENV \
  #           $SANITY_TOKEN \
  #           $YT_API \
  #           $CONTAINER_REGISTRY \
  #           $TAG
  #         pushWebsite \
  #           $CONTAINER_REGISTRY \
  #           $TAG
  #         deployWebsite \
  #           $ALV_HOSTNAME \
  #           $TAG