name: Deploy test website

on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  ENV: test
  TAG: en-eller-annen-tag

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    outputs:
      alvHostname: ${{ steps.get_secrets.outputs.alvHostname }}
      sanityToken: ${{ steps.get_secrets.outputs.sanityToken }}
      youtubeApiToken: ${{ steps.get_secrets.outputs.youtubeApiToken }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Secret from Azure Key Vault
        id: get_secrets
        run: |
          # Log in to Azure
          az login --service-principal \
            -u "${{ vars.AZURE_CLIENT_ID }}" \
            -p "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ vars.TENANT_ID }}"
          
          # Set subscription
          az account set --subscription "${{ vars.SUBSCRIPTION_ID_TEST }}"

          # Get secrets from key vault
          ALV_HOSTNAME=$(az keyvault secret show --name "alv-hostname" --vault-name "${{ vars.KEY_VAULT_TEST }}" --query "value" -o tsv)
          SANITY_TOKEN=$(az keyvault secret show --name "sanity-token" --vault-name "${{ vars.KEY_VAULT_TEST }}" --query "value" -o tsv)
          YOUTUBE_API_TOKEN=$(az keyvault secret show --name "youtube-api-token" --vault-name "${{ vars.KEY_VAULT_TEST }}" --query "value" -o tsv)

          # Set job outputs
          echo "alvHostname=$ALV_HOSTNAME" >> $GITHUB_OUTPUT
          echo "sanityToken=$SANITY_TOKEN" >> $GITHUB_OUTPUT
          echo "youtubeApiToken=$YOUTUBE_API_TOKEN" >> $GITHUB_OUTPUT
  deploy-website:
    needs: get-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
      - uses: azure/setup-kubectl@v3
      - name: Build, push and deploy
        shell: bash
        run: |
          ALV_HOSTNAME=${{ needs.get-secrets.outputs.alvHostname }}
          SANITY_TOKEN=${{ needs.get-secrets.outputs.sanityToken }}
          YOUTUBE_API_TOKEN=${{ needs.get-secrets.outputs.youtubeApiToken }}

          # Authenticate Azure container registry
          docker login ${{ vars.CONTAINER_REGISTRY }} \
            --username ${{ vars.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }}

          # Source website service
          source ./packages/website/website-service.sh
          
          # Build
          buildWebsite $ENV $SANITY_TOKEN $YOUTUBE_API_TOKEN ${{ vars.CONTAINER_REGISTRY }} $TAG
          
          # Push
          pushWebsite ${{ vars.CONTAINER_REGISTRY }} $TAG
          
          # Deploy
          deployWebsite $ALV_HOSTNAME ${{ vars.CONTAINER_REGISTRY }} $TAG