name: Deploy test website

on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  ENV: test
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  KEY_VAULT: ${{ vars.KEY_VAULT_TEST }}
  TAG: en-eller-annen-tag

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    outputs:
      alvHostname: ${{ steps.get_secrets.outputs.alvHostname }}
      sanityToken: ${{ steps.get_secrets.outputs.sanityToken }}
      youtubeApiToken: ${{ steps.get_secrets.outputs.youtubeApiToken }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Secret from Azure Key Vault
        id: get_secrets
        run: |
          az login --service-principal -u "${{ vars.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ vars.TENANT_ID }}"
          az account set --subscription "${{ vars.SUBSCRIPTION_ID_TEST }}"

          ALV_HOSTNAME=$(az keyvault secret show --vault-name $KEY_VAULT_TEST --name alv-hostname --query "value" -o tsv)
          SANITY_TOKEN=$(az keyvault secret show --vault-name $KEY_VAULT_TEST --name sanity-token --query "value" -o tsv)
          YOUTUBE_API_TOKEN=$(az keyvault secret show --vault-name $KEY_VAULT_TEST --name youtube-api-token --query "value" -o tsv)

          echo "$ALV_HOSTNAME $SANITY_TOKEN $YOUTUBE_API_TOKEN"

          echo "alvHostname=$ALV_HOSTNAME" >> $GITHUB_OUTPUT
          echo "sanityToken=$SANITY_TOKEN" >> $GITHUB_OUTPUT
          echo "youtubeApiToken=$YOUTUBE_API_TOKEN" >> $GITHUB_OUTPUT
  deploy-website:
    needs: get-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build, push and deploy
        shell: bash
        run: |
          ALV_HOSTNAME=${{ needs.get-secrets.outputs.alvHostname }}
          SANITY_TOKEN=${{ needs.get-secrets.outputs.sanityToken }}
          YOUTUBE_API_TOKEN=${{ needs.get-secrets.outputs.youtubeApiToken }}

          # Source website service
          source ./packages/website/website-service.sh
          
          # Build
          buildWebsite $ENV $SANITY_TOKEN $YOUTUBE_API_TOKEN $CONTAINER_REGISTRY $TAG
          
          # Push
          pushWebsite $CONTAINER_REGISTRY $TAG
          
          # Deploy
          deployWebsite $ALV_HOSTNAME $TAG