name: Deploy Sanity

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --immutable

      - name: Deploy Sanity
        run: |
          yarn workspace cms run graphql-deploy
          yarn workspace cms run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.DEPLOY_SANITY_STUDIO }}
