name: Deploy website

on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  ENV: test
  CONTAINER_REGISTRY: alvkubernetesclustertestacr.azurecr.io
  ALV_HOSTNAME: TODO
  SANITY_TOKEN: TODO
  YT_API: TODO
  TAG: TODO

jobs:
  deploy_website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build, push and deploy
        shell: bash
        run: |
          source ./packages/website/website-service.sh
          buildWebsite \
            $ENV \
            $SANITY_TOKEN \
            $YT_API \
            $CONTAINER_REGISTRY \
            $TAG
          pushWebsite \
            $CONTAINER_REGISTRY \
            $TAG
          deployWebsite \
            $ALV_HOSTNAME \
            $TAG