name: PR & Build

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn --immutable

      - name: Linting
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Sanity configcheck
        run: yarn workspace cms run sanity configcheck
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.DEPLOY_SANITY_STUDIO }}
          SANITY_DATASET: development

      - name: Build
        run: yarn workspace website run build
        env:
          DEBUG: sanity
          SANITY_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
